spring.application.name=kannect-user-service
server.port=8080


email.service.url=http://localhost:3000/forum

spring.datasource.url=jdbc:postgresql://dpg-d0a1571r0fns73e0melg-a.singapore-postgres.render.com:5432/kannectdb
spring.datasource.username=admin
spring.datasource.password=pAdo1Zeme66SHatZmtFnpF9CFklo2Ugx
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


jwt.secret=2e23d7dc-3ab6-4fcd-b698-ede98aab8539
jwt.expiration=3600000

security.login.decryption.key=2e23d7dc-3ab6-4fcd-b698-ede98aab
security.login.decryption.algorithm=AES


spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/databasechangelog.yaml


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


kannect.wallet.initialCoins=0


aws.s3.bucket-name=kannect-profile-photos
aws.access-key=YOUR_AWS_ACCESS_KEY
aws.secret-key=YOUR_AWS_SECRET_KEY
aws.region=ap-south-1


gcp.project-id=your-gcp-project-id
gcp.bucket-name=your-gcp-bucket-name
gcp.credentials.path=/path/to/your/service-account.json

cloudinary.cloud-name=dkjpkeczx
cloudinary.api-key=135293889366384
cloudinary.api-secret=AWHEGPe4uQXAUWE8Wr2yLOcoqfk
