spring.application.name=kannect-user-service
server.port=8080


email.service.url=http://localhost:8090

spring.datasource.url=jdbc:postgresql://localhost:5432/kannectdb
spring.datasource.username=postgres
spring.datasource.password=yourStrongPassword
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.data.redis.host=localhost
spring.data.redis.port=6379


jwt.secret=2e23d7dc-3ab6-4fcd-b698-ede98aab8539
jwt.expiration=3600000

security.login.decryption.key=2e23d7dc-3ab6-4fcd-b698-ede98aab
security.login.decryption.algorithm=AES


spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/databasechangelog.yaml


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


kannect.wallet.initialCoins=0


aws.s3.bucket-name=kannect-profile-photos
aws.access-key=YOUR_AWS_ACCESS_KEY
aws.secret-key=YOUR_AWS_SECRET_KEY
aws.region=ap-south-1


gcp.project-id=your-gcp-project-id
gcp.bucket-name=your-gcp-bucket-name
gcp.credentials.path=/path/to/your/service-account.json


